app:
  baseUrl: https://backstage.mycompany.com  # Replace with your Ingress or AKS FQDN

backend:
  baseUrl: https://backstage.mycompany.com
  listen: ':7007'

  database:
    client: pg
    connection:
      host: postgres-service
      port: 5432
      user: backstageuser
      password: yourpassword123
      database: backstage_db
      ssl: false
        #rejectUnauthorized: false  # If you're using a managed PostgreSQL with SSL like Azure PG

auth:
  providers:
    guest: {}

catalog:
  locations:
    - type: file
      target: ./examples/entities.yaml
    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
