apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-demo
  template:
    metadata:
      labels:
        app: backstage-demo
    spec:
      containers:
        - name: backstage
          image: mybsacr.azurecr.io/backstage-demo:latest
          ports:
            - containerPort: 7007
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgresuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgrepass
            - name: POSTGRES_DB
              value: backstage
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: githubToken
            - name: AZURE_DEVOPS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: azureDevOpsToken
            - name: JIRA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: jiraToken
            - name: JIRA_EMAIL_SUFFIX
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: jiraEmailSuffix
            - name: K8S_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: k8sToken
            - name: K8S_CA_DATA
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: k8sCaData
          volumeMounts:
            - name: config-volume
              mountPath: /app/app-config.yaml  # Changed from app-config.production.yaml
              subPath: app-config.yaml         # Must match key in ConfigMap
      volumes:
        - name: config-volume
          configMap:
            name: backstage-config
