apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-jira-issue
  title: Create JIRA Issue
  description: A template to create a JIRA issue from Backstage
spec:
  owner: team-devops
  type: service

  parameters:
    - title: JIRA Issue Details
      required:
        - projectKey
        - issueType
        - summary
        - description
      properties:
        projectKey:
          title: Project Key
          type: string
          description: Enter the JIRA project key (e.g., DEV, ITSM)
        issueType:
          title: Issue Type
          type: string
          description: Type of JIRA issue (Bug, Task, Story)
          enum:
            - Bug
            - Task
            - Story
        summary:
          title: Issue Summary
          type: string
        description:
          title: Issue Description
          type: string
          format: textarea

  steps:
    - id: createJiraIssue
      name: Create JIRA Issue
      action: jira:createIssue
      input:
        projectKey: ${{ parameters.projectKey }}
        issueType: ${{ parameters.issueType }}
        summary: ${{ parameters.summary }}
        description: ${{ parameters.description }}

  output:
    links:
      - title: View Created Issue
        url: https://nandamarri.atlassian.net/jira/${{ parameters.projectKey }}-${{ steps.createJiraIssue.output.issueId }}
