name: Build and Deploy to AKS

on:
  push:
    branches:
      - none

env:
  ACR_NAME: mybsacr.azurecr.io
  IMAGE_NAME: backstage-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker Login to ACR
      run: az acr login --name mybsacr

    - name: Build and Push to ACR
      run: |
        docker build -t $ACR_NAME/$IMAGE_NAME:latest .
        docker push $ACR_NAME/$IMAGE_NAME:latest

    - name: Get AKS Credentials
      run: az aks get-credentials --resource-group bsrgp --name myBSCluster

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Verify Deployment
      run: kubectl get all
